### ISSUE TITLE
Including multiple Sphinx projects in a LaTeX file and linking between them?

### ISSUE THREAD

**Issue by mgeier** [mossblaser/intertex#1]
First of all, thanks for providing this extension!

I am looking for a similar functionality, but not quite, and I thought I'll ask if you have some ideas how to do that.

I want to include multiple Sphinx projects in a singe LaTeX file, leading to a single PDF in the end.

An example for how I'm planning to do that is here: https://github.com/spatialaudio/nbsphinx/pull/719

In my case I would have two Sphinx projects and one of them already uses `intersphinx` to link to the other, and I would like those links to be turned into references to the appropriate PDF page in the combined PDF.

Did you happen consider something like that already?

Do you think `intertex` could be extended to cover this use case?

**Comment by mossblaser** [comment]
It's not something I had thought of but it clearly seems desirable thing to want to do!

In good news,  LaTeX sphinx builds use latex's own mechanism for crossreferencing which naturally suggests you might be able to make two crudely concatenated latex sources reference eachother by ensuring they use consistent keys. The code in this repo interacts pretty intimately with the bits of sphinx responsible for doing this so may be of help.

The bad news is that Sphinx's internal design doesn't quite fit the model of deferring some tasks to another tool and so my recollection is that this behaviour is all "hacked in" and quite ugly to tweak. The LaTeX backend generally lacks any semblance of the elegance that other bacjends have. However the intersphinx sources contain many frustrated comments which I hope might prove helpful in telling you where to look. There is no small irony in finding that a documentation gerator has such limited documentation!

I think intersphinx itself might not be a good starting point since it actually operates the opposite way to what you're hoping to do by pulling page numbers out of other documents' LaTeX build files and manually burning the references into sphinx documents during the translation into LaTeX. For your use you will probably be trying to defer the whole job to LaTeX which is probably going to look a whole lot saner on the plus side (fingers crossed!)

I'm sorry I probably can't offer much help, however, as it has been some years since I've had my head in this space. But in any case, expect to come away from this slightly emotionally scarred and a little more famille with Sphinx's internals. 

Best of luck!

**Comment by mgeier** [comment]
Sorry for my late response! It took me a while to find the time to try this out, but in the end it was more straightforward than I thought!

For future reference, and in case somebody stumbles over this, here's how I did it:

As mentioned, I have 2 separate Sphinx projects, let's call them project A and B. B contains `intersphinx` links to A.

First, in the `conf.py` of project A, I had to force the generation of the `intersphinx` inventory file `objects.inv`, because this is by default only built for HTML output. I guess this manipulation is not strictly necessary, because one could simply build the HTML output as well just to get the inventory file.

In the `conf.py` of project B, I used Sphinx's `InventoryFile` to load the `objects.inv` from project A (using a hard-coded path). I then used this data in the `missing-reference` event handler. I could use the `reftarget` from the passed-in `node` to look up the appropriate record in the inventory. Then I simply created a `docutils.nodes.reference` node using the third entry from the record as `refuri` argument. And then I appended a `docutils.nodes.Text` node containing the fourth entry.

The link text can potentially be overwritten in the reST source file, but this case is easy to detect with `node['refexplicit']`. In this case I did not use the information from the inventory but `node.astext()` instead.

And that's all! No manual parsing of anything, no concatenating of labels, no juggling with LaTeX-specific labels, just using the strings that are already there.

----

Thanks for your help, you gave me the initial ideas where to start looking!
